---
- name: ensure variables
  fail:
    msg:
      - "Please make sure this variables are set:"
      - "prometheus_file_sd_target_name"
      - "prometheus_file_sd_target_port"
  when: not prometheus_file_sd_target_name or
    not prometheus_file_sd_target_port
