---
galaxy_info:
  role_name: prometheus_file_sd
  author: Roman Kuzmitskii
  description: prometheus file sd role
  license: GPLv2
  min_ansible_version: 2.8
  galaxy_tags:
    - monitoring
    - prometheus
    - system
  platforms:
    - name: Debian
      versions:
        - buster
    - name: EL
      versions:
        - 7
dependencies: []
