---
galaxy_info:
  author: Roman Kuzmitskii <ansible@damex.org>
  description: prometheus file sd role
  license: GPLv2
  min_ansible_version: 2.14.2
  platforms:
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
dependencies: []
